### ISSUE TITLE
Unknown column 'offers_help_3' in 'where clause'

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.mutualaid#11]
As reported in #8, this error would come up, when certain help types are offered/present, but not enabled (any more).

**Comment by bjendres** [comment]
@vingle, could you try again with ``1.1-alpha3`` (https://github.com/systopia/de.systopia.mutualaid/releases/tag/1.1-alpha3)

**Comment by vingle** [comment]
Yes, that fixed it!

**Comment by bjendres** [comment]
Cool, thanks!
