### ISSUE TITLE
Make Unconfirmed Matches report easier to find after clicking 'Match Now'? #enhancement

### ISSUE THREAD

**Issue by vingle** [systopia/de.systopia.mutualaid#13]
The Unconfirmed Matches report (ie /civicrm/civicrm/report/instance/38?force=1&reset=1) is within Reports which might be hard to find for a new comer. 

To help with workflow, could it either be:
 - added to the Mututal Aid menu?
 - auto-redirected on clicking 'Match Now'

**Comment by bjendres** [comment]
It *was* added to the mutual aid menu, but then @jensschuppe renamed it with 417ca2870437cefd8a61ffe5a4a7b07e741e806f, which made it drop out of the menu again.

@jensschuppe what's the reason for this? can we just change it back?

**Comment by jensschuppe** [comment]
Sorry, I didn't know the navigation menu link was dependent on the report name. I just wanted to have names consistent.

So, either renaming the report or adjusting the navigation menu link would be fine I think.

**Comment by bjendres** [comment]
The link is now in the menu (again) with ``1.1-beta1``.

I would advise against automatic redirect after 'match now', as it enforces a certain workflow on people. It could be very annoying if that's not what you want. But feel free to re-open the ticket if you disagree.
