### ISSUE TITLE
Feature suggestion: Free HTML regions for quick UI/UX - dashboard, landing page & header

### ISSUE THREAD

**Issue by vingle** [systopia/de.systopia.mutualaid#17]
There's three features here, but depending how they were implemented perhaps they fit together (or perhaps they should be unique extensions). Two are more specifically for standalone installs not using any of the CMS they're installed within, like Spark, to let the user customise basic landing page & header. The other is a general admin dashlet that doesn't need to be end-user configurable. Maybe all three could for now maybe be rich text editor-generated regions?

**1. Admin dashboard / dashlet** - listing key links - not just within the extension but that may be of use within Civi, such as bulk email, as well as reference to help docs, community support, etc. Potentially, one day (v2!) could also summarise stats, like signups or matched/unmatched listings.

**2. Landing page (standalone orientated)** - provide a rich text editor to creaste a simple front-page for Mutual Aid Groups whose current web presence is either just a Facebook or Whats App group - and are using something like Spark to get forms & CRM up quickly. Could be free for the end-user to configure however they wish - contact info, code of conduct, useful links, update notices - could also have some set fields - ie name of group to ensure key info like group name and location is crawler-friendly.

**3. Header/nav (standalone orientated)** - a way to add a group name or logo in the header of each page, and for end users to add key links as a simple one-tier nav, ie pointing to forms or terms of service.

**Comment by vingle** [comment]
If of use/interest - have added an Admin Dashboard (simple layout with some inline css: https://github.com/vingle/de.systopia.mutualaid/commit/064a92384aa7167173c96da73a7c2a9b3b93a9f1)

<img width="1593" alt="image" src="https://user-images.githubusercontent.com/1175967/79286335-2fd82c80-7eb8-11ea-8c3a-5dc313aa528b.png">

**Comment by bjendres** [comment]
Looks great, @vingle! Could you create a PR for this?

**Comment by vingle** [comment]
Will do @bjendres – I need to tidy up the html a bit - at the moment it's not loading as an actual dashlet, but just as a block of html at the top of the dashboard that you can't control (minise, expand, delete) as with other dashlets. It's [more complex](https://docs.civicrm.org/dev/en/latest/api/v3/changes/#44-dashboard-api-enable-developers-to-register-new-dashlets), but what do you think about adding it as an actual dashlet?

**Comment by vingle** [comment]
I included a number of features that aren't availble without further configuration/work. Taking those out - in case there are any suggested editions/edits - the list would be

**Gather**
- Import data
- Add individual
- Help offer form
- Help request form

**Communicate**
- Find people (Advanced search)
- Manage contact groups
- Send bulk email

**Match**
- Match requests and offers
- Unconfirmed matches
- Unmatched requests

**Configure and setup**
- Mapping/Geocoding setup
- General configuration
- Specify help categories
- Create default emails

![image](https://user-images.githubusercontent.com/1175967/81805185-4c48a280-9512-11ea-9b73-efe17b85cb4e.png)

**Comment by bjendres** [comment]
Looks pretty helpful. And cool. Go for it!

**Comment by vingle** [comment]
I've turned what I did before into a Dashlet: https://github.com/vingle/de.systopia.mutualaid/commit/df0a3ba8bf83a532041f2967b65133d88856ab91

However, before I make a PR there's two issues held back by my lack of knowledge:

- how to add the Dashlet into the `civicrm_dashboard` table on install/enable - I just added it manually on my local instance (and ideally into `civicrm_dashboard_contact` too so it appears loaded by default)
- the links to the two reports (_unconfirmed matches_ and _unconfirmed requests)_ - are pointing at specific report IDs which I'm assuming change depending on the install. Is there another way to link to specific reports?

![image](https://user-images.githubusercontent.com/1175967/81931906-b9c40400-95e2-11ea-99f3-5131902b9f38.png)

![image](https://user-images.githubusercontent.com/1175967/81932479-cac14500-95e3-11ea-9d5d-88ff4a7a3b88.png)

**Comment by bjendres** [comment]
Thanks @vingle!
I created branch issue/17 for this. I just added an upgrader to install the dashboard, fixed the links, and added translation.

I did not automatically install the dashlet on the user's dashboard, that seemed a little intrusive to me.

@vingle do you want to give it a try before I merge it?

**Comment by vingle** [comment]
Thanks @bjendres! 

It didn't add the dashlet to the database on install - I've ammended upgrader.php here: https://github.com/vingle/de.systopia.mutualaid/commit/1ce072ad446202e3cd3f5d35c24a09d2934f20ea by copying the dashlet api from upgrade to install function and that seemed to work. Shall I PR that change?

**Comment by bjendres** [comment]
@vingle What do you think? Are we ready to merge into ``master``?

**Comment by vingle** [comment]
@bjendres all looks good to me.

**Comment by bjendres** [comment]
Ok, it's merged. Will be released with ``1.2``

**Comment by vingle** [comment]
Closing as this now covers item 1 in original issue, while items 2 & 3 specifically applied to Spark (anyone else could use their CMS) – and that's probably better handled outside of this extension.
