### ISSUE TITLE
Beta test help type matching

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.mutualaid#2]
The first user of the extension was only using the general help type, so the matching for individual help types has not been properly tested yet.

Please get in contact if you do want to use this feature.

**Comment by bjendres** [comment]
@vingle Please let me know when you think that ``1.1.beta1`` is sufficiently tested for a proper relase

**Comment by vingle** [comment]
Some tests quickly done:
- installs on spark and standard drupal and all links work without error
- matches up and makes a relationship based on help types (inc. custom help types) as expected. Tested with Google not OSM yet.
- _Small Usability issue_ - some fields need to have a value so either need to be required or have a value set but hidden. ie without country/postcode it cannot geocode, without min distance or number of people it cannot match. But these don't need to be displayed if they have a default value set.
- Changing help types offered and re-running the match - works.
- _Question_: should setting 'Personal Contact Possible' on the requestee's record add a permission to the matched person's relationship 'access information'? Or after Help Status is changed? Or is it a flag for the administrator to adjust the permissions. Maybe that's a seperate question - but basically what happens after a match is made? Should CiviRules send an email to both parties with contact details once the help status has changed?

Things not tested yet if anyone else is testing:
- Bulk matching / reporting: have only tested one-to-one contact matches (need to prepare a data set with geocodable addresses and properly formatted help offers/requests).
- ACL - are there specific permissions that can be tested? Presumably this is intended as two tier at present - registrants who never login / can't edit their details; and admins who can do everything?
- Language matching
- Custom welcome message sending
- Integration with other extensions, ie CiviRules
- Other CMSs
- Multilingual integration

**Comment by bjendres** [comment]
Thanks for testing, @vingle!!

> Small Usability issue - some fields need to have a value so either need to be required or have a value set but hidden. ie without country/postcode it cannot geocode, without min distance or number of people it cannot match. But these don't need to be displayed if they have a default value set.

In the designated form you cannot leave it empty, but you can, unfortunately, enter zero. We should change that, see #14. Please note, that you can also set a default value in the settings (at the bottom), and then also disable the field in the form altogether. In the backend, you cannot make the fields mandatory (otherwise you can't create any contact without it), so you just have to keep an eye on it. I think it would make sense to create a "problematic cases" report, but that's a bit of work, I guess. See #15

> Question: should setting 'Personal Contact Possible' on the requestee's record add a permission to the matched person's relationship 'access information'?

No, sorry, this is ambiguously named. It meant to say: can the helper see the person in with close proximity or not, i.e. if the person requesting help has the 'rona.

> Maybe that's a seperate question - but basically what happens after a match is made? Should CiviRules send an email to both parties with contact details once the help status has changed?

I suggest that somebody reviews the matched contacts, calls them both, then adjusts the status to ``confirmed`` or ``communicated``, and then maybe sends an email to both. You *could* automate that, but I guess you'd want to keep an eye open for scammers and fraudsters. @jensschuppe can tell you how the sending out of the emails works (if you select a template in the settings).

**Comment by vingle** [comment]
That makes a lot of sense, thanks. Probably worth having some basic email templates setup for the Spark setup, will make a note.

> No, sorry, this is ambiguously named.

I see. Something like 'Am isolating, no direct contact' - I guess this is a status that can change between the point of submitting the form and the task happening - so maybe better to encourage safeguarding to be established in the communications between volunteer and requestee (not that that's a tech issue, more wording/docs).

While it'd be good to have more people test this in more scenarios -  in my limited tests - the beta seems pretty solid.

**Comment by jensschuppe** [comment]
The e-mail template setting is used for sending a confirmation to the person submitting the forms (same template for both forms, supposed to send something like "Thank you for your submission, we will contact you when there is a match.").

There is no e-mail being sent when matching help requests to offers.

**Comment by bjendres** [comment]
I'm closing this, thanks @vingle
