### ISSUE TITLE
Fields vanish on the config screen in some situations

### ISSUE THREAD

**Issue by vingle** [systopia/de.systopia.mutualaid#20]
Sorry this bug isn't more detailed - this is a behaviour I experienced once - and you can currently see it on the demo at: https://corona.civicrm.jaapjansma.nl/. Here it's the fields from Prefix until Lattitude (including address & name) that are missing ->

![image](https://user-images.githubusercontent.com/1175967/78304433-a67b3e80-7536-11ea-8780-9203259e691b.png)

**Comment by bjendres** [comment]
@jensschuppe does this make sense to you?

**Comment by jensschuppe** [comment]
From the Covid-19 channel on chat.civicrm.org (which I suppose is the same issue as described here)

The extension determines which fields are available when the settings cache is generated. That is, changing individual or address field configuration at civicrm/admin/setting/preferences/display?reset=1 requires a cache clear for the mutualaid settings to take up these changes. Does clearing the cache solve the issue?

> That's fixed it - tho not sure if it was the clearing caches or the upgrade that fixed it?

@vingle Can you confirm that there's nothing else wrong with the fields after clearing caches?

**Comment by vingle** [comment]
> From the Covid-19 channel on chat.civicrm.org (which I suppose is the same issue as described here)
> 
> The extension determines which fields are available when the settings cache is generated. That is, changing individual or address field configuration at civicrm/admin/setting/preferences/display?reset=1 requires a cache clear for the mutualaid settings to take up these changes. Does clearing the cache solve the issue?
> 
> > That's fixed it - tho not sure if it was the clearing caches or the upgrade that fixed it?
> 
> @vingle Can you confirm that there's nothing else wrong with the fields after clearing caches?

After Jaap both cleared caches and updated his demo site from 1.1-dev to latest, it was fixed. Presumably that was the caching.

**Comment by jensschuppe** [comment]
Thanks for the prompt feedback @vingle!

**Comment by vingle** [comment]
As flushing CiviCRM caches isn't straightforward - would it be viable to either flush caches on page save, or add a flush cache button? My understanding (which could be wrong) is that you can only flush CiviCRM caches thru SSH or ftp, unless something like https://www.drupal.org/project/civicrm_clear_all_caches is installed.

**Comment by jensschuppe** [comment]
Flushing caches is possible on the Drupal admin UI (not sure about WordPress and Joomla) and also by calling `civicrm/menu/rebuild`.

There's only a need for flushing caches when you change something on the civicrm/admin/setting/preferences/display settings page. So this should be a quite administrative task which is usually not done that often. Maybe this behavior can be mentioned in the docs of this extension.

**Comment by vingle** [comment]
> by calling civicrm/menu/rebuild

Ah, that's the one - thanks. I tried flushing cache's on Jaap's demo via admin/config/development/performance - but it didn't make any difference. I normally use flush-all from the admin menu drop down but it's not installed. Not sure if that's the same process - or if either of these methods clears tempaltes_c files & civi-specific cache. 

> There's only a need for flushing caches when you change something on the civicrm/admin/setting/preferences/display page

That's strange – when this bug emerged for me earlier in the week when I noticed the country field wasn't in config - I hadn't touched that page (I had maybe disabled some profiles/custom field sets?). But the issue was resolved before I could document it so don't have more information I'm afraid.

**Comment by bjendres** [comment]
@jensschuppe Couldn't we just show a popup when changing the configuration saying: "if you have changed anything in the form layout, please press ``here`` to clear the CiviCRM cache"?

**Comment by jensschuppe** [comment]
The cache will have to be cleared when making changes to CiviCRM core display settings, not the extension settings. So the popup will have to be shown after submitting the core display settings form.

**Comment by bjendres** [comment]
Ah, ok, I misunderstood. Thanks
