### ISSUE TITLE
Required select fields accept "- None -" etc. as valid option

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.mutualaid#21]
This produces errors like `'0' is not a valid option for field county_id`.

This applies to those fields:
- prefix_id
- suffix_id
- county_id
- state_province_id
- country_id

The extension uses `0` as value for those "- None -" or "- Select -" options. Instead, the empty string `''` should be used.

**Comment by jensschuppe** [comment]
Forgot to crosslink commit f304f4cebeebb0739d4f788c906980e9d16bd3c1

**Comment by jensschuppe** [comment]
Released with `1.0-beta2` and merged into `master` for the next `1.1.x` release.

**Comment by bjendres** [comment]
Has also been released in ``1.1``.

@jensschuppe can we close this?

**Comment by jensschuppe** [comment]
Sure, that seems to work.
