### ISSUE TITLE
Customising the forms

### ISSUE THREAD

**Issue by StijnVanhandsaeme** [systopia/de.systopia.mutualaid#24]
This might be something very trivial I am missing but I am not finding how to edit some fields in the forms that are not on the settings page. For instance it is now showing 'Supplemental address 1, 2, 3'  as obligatory.
Where could I edit this? The only way I found was to deselect those in the general civicrm address options.

**Comment by vingle** [comment]
Are you you saying those did not appear on the Mutual Aid config screens? Sounds like it could be linked to this issue: https://github.com/systopia/de.systopia.mutualaid/issues/20. If you flush Civi cache (visit civicrm/menu/rebuild) do they appear again?

**Comment by StijnVanhandsaeme** [comment]
Yes indeed that seems to just have solved it. Thank you very much!
